-- 修复数据库表结构问题
-- 确保所有表都有正确的字段定义

USE blacklist;

-- 检查并修复用户表
-- 确保用户表有所有必需的字段
ALTER TABLE users 
MODIFY COLUMN last_login TIMESTAMP NULL COMMENT '最后登录时间';

-- 检查并修复黑名单表
-- 确保黑名单表有id字段（如果不存在）
ALTER TABLE blacklist 
ADD COLUMN IF NOT EXISTS id INT PRIMARY KEY AUTO_INCREMENT FIRST;

-- 检查并修复黑名单历史表
-- 确保黑名单历史表有id字段（如果不存在）
ALTER TABLE blacklist_history 
ADD COLUMN IF NOT EXISTS id INT PRIMARY KEY AUTO_INCREMENT FIRST;

-- 修复筛查结果表的字段类型
ALTER TABLE screening_results 
MODIFY COLUMN is_verified BOOLEAN DEFAULT FALSE COMMENT '是否已验证';

-- 修复系统配置表的字段类型
ALTER TABLE system_configs 
MODIFY COLUMN is_editable BOOLEAN DEFAULT TRUE COMMENT '是否可编辑';

-- 确保所有表都有is_active字段（如果不存在）
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE roles 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE blacklist 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE screening_tasks 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE screening_results 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE system_configs 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

ALTER TABLE operation_logs 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用';

-- 确保所有表都有created_at和updated_at字段
ALTER TABLE permissions 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE roles 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE blacklist 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE blacklist_history 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE screening_tasks 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE screening_results 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE system_configs 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE operation_logs 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 显示表结构验证
SHOW TABLES;
DESCRIBE users;
DESCRIBE roles;
DESCRIBE blacklist;
DESCRIBE screening_results;
DESCRIBE system_configs;

COMMIT;
